### ISSUE TITLE
Installation Failure in Pillow req when Brew's JPEG package isn't installed

### ISSUE THREAD

**Issue by tom-price** [holgerd77/django-dynamic-scraper#108]
The Pillow requirement attempted to be installed by DDS has a dependancy with `brew jpeg` and throws the following error when installed either direct from GitHub or via Pip on OSX 10.13.4 and Python version 3.6.4.

`ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting`

[Pillow's OSX's installation instructions](https://pillow.readthedocs.io/en/3.0.x/installation.html) detail how to add these dependancies.
`brew install libtiff libjpeg webp little-cms2`

**Comment by tyknot** [comment]
I'm getting this same error when trying to install this package, but with Windows 8,1, Python 3.6.4 and my ValueError is zlib.

`ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting`

Is there a fix for this?

**Comment by Abhijeet321** [comment]
Anyone knows the fix?

**Comment by tyknot** [comment]
I fixed it by `easy_install`

Another fix may be installing older versions of pip, it doesn't seem to install correctly with pip versions > 9

**Comment by nsaklas** [comment]
same boat here.  Can't do pip install or easy_install citing the following:

 File "C:\xxx\easy_install-uum8gtoc\Pillow-3.4.2\setup.py", line 521, in build_extensions
ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

would love if anyone has assistance for moving past this...

**Comment by holgerd77** [comment]
Should be fixed by `Pillow` version upgrade in latest [0.13.2](https://django-dynamic-scraper.readthedocs.io/en/0.13-dev/development.html#release-notes) release, will close.
