### ISSUE TITLE
can't install django-dynamic-scraper with django 1.9 and python 3.6

### ISSUE THREAD

**Issue by felipeharry2** [holgerd77/django-dynamic-scraper#115]
Hi I cant install it, error message:

 path\Wondershare\CreatorTemp\pip-install-5eut7xdz\pillow\setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

How could I fixed it please ? :)

**Comment by holgerd77** [comment]
This is probably an issue with a too old `Pillow` dependency, see e.g. [here](https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux).

Will release a bug fix release soon.

**Comment by holgerd77** [comment]
Fixed in [0.13.2-beta](https://django-dynamic-scraper.readthedocs.io/en/0.13-dev/development.html#release-notes) release.
