### ISSUE TITLE
django-dynamic-scrapy do not work with python3.x after upgrading

### ISSUE THREAD

**Issue by karajah90** [holgerd77/django-dynamic-scraper#132]
i am using Scrapy (1.1.2) with Django (1.8.19) and Django dynamic scrapy (0.11.2) on python (2.7), its works fine with me but after upgrading to python 3 i got errors in logs when my spiders run as follow :

```
File "/root/.pyenv/versions/3.4.10/envs/3.4.10/lib/python3.4/site-packages/scrapy/loader/__init__.py", line 154, in _get_item_field_attr
    value = self.item.fields[field_name].get(key, default)
KeyError: 'photos'
```

i tried to use many python versions (3.4.x, 3.5.x, 3.6.x) with many versions of Django dynamic scrapy but still the problem appears, so the result which i arrived to it that this package do not support python 3 although the documentation says it support pyhthon 3.

my question is which part in this packed occurred this problem and where in need to edit in the core of this package to make my upgrade success ?

**Comment by samthaman** [comment]
I'm totally new to this package (found it like 5 minutes ago), but I'm pretty sure that I saw they'd dropped 3.4 support when I was reading the docs. I know you said you tried multiple versions, but I thought I'd mention it because you example references 3.4. good luck
