### ISSUE TITLE
Using dynamic XPaths based on response.data

### ISSUE THREAD

**Issue by amyth** [holgerd77/django-dynamic-scraper#43]
What I am trying to achieve is a little complex, I am looking to somehow dynamically use a Xpath for a `scraped_obj_attr` in a particular `scraper` class. To put this into simple words, say I have the following Django model that I want to populate using DDS:

```
class Article(models.Model):
    title = models.CharField(max_length=200)
    news_website = models.ForeignKey(NewsWebsite)
    description = models.TextField(blank=True)
    url = models.URLField()
    checker_runtime = models.ForeignKey(SchedulerRuntime, blank=True, null=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.title
```

I have created the required `ScrapedObjectClass`, `Scraper` and `NewsWebsite` objects. Now in the scraper class I use the `scraped_obj_attrs` that were defined in the associated `scraped_object_class`.

This runs fine. In my use case I have article pages where the required information is present in multiple elements and I want to pick it up from the most relevant element.

Say, An article page has `og` tags like `<meta property="og:title" ... >` and has `<h1 class="title"> ...</h1>` both containing the same information that I want to feed to the title field in my `Article` model. The `og` tag thing is optional and only present in some article pages. I want to check if the `og` tags are present in response then use an Xpath to get the information from the `og` tag (example: `//meta[contains(@property, "og:title")]/@content`) and if it's not there in the response then use Xpath for h1 element (example: `//h1[@class="title"]/text()`)

Is the above currently somehow achievable by DDS ? If yes, could you point me in the right direction. If not, could you make this a feature request.

Thanks,

Amyth

**Comment by rakanalh** [comment]
Your question is mainly an XPath dependant. You could use the OR operator in XPath to fetch a value from either one of your expressions.

So 
```
//meta[contains(@property, "og:title")]/@content) | //h1[@class="title"]/text()
```

Should be sufficient.

**Comment by amyth** [comment]
@rakanalh Thanks, figured it out :)

**Comment by amyth** [comment]
@rakanalh Thanks, figured it out :)
