### ISSUE TITLE
TakeFirst vs Returning multiple elements found

### ISSUE THREAD

**Issue by holgerd77** [holgerd77/django-dynamic-scraper#45]
Post on mailing list from Rakan:

Hello,

I've posted about scraping multiple images using DDS previously on this group. However, i discovered that if you're capturing an article (example) with a body inside multiple paragraph tags, you'll only get the first one. Digging through this detail, i found out that the DjangoSpider was defining:
1) _get_processors
procs = [TakeFirst(), processors.string_strip,] 
as the default processors
and
2) self.loader.default_output_processor = TakeFirst()

Do you think this was a correct design decision given that it adds the restriction of ending up with 1 element only xpath or regex? I believe DDS should allow the flexibility of returning multiple elements and users would need to use TakeFirst in case they only need the first element.

Thanks,
Rakan

**Comment by rakanalh** [comment]
Basically this is the implementation i had in one of my projects using DDS. It basically takes all values, strips them and returns the non-empty values.
