### ISSUE TITLE
Future developments of this repo?

### ISSUE THREAD

**Issue by rakanalh** [holgerd77/django-dynamic-scraper#49]
Hello @holgerd77,

Any plans on developing this app any further?

**Comment by holgerd77** [comment]
Hi Rakan,
I actually will do some work on it today - will try to update Scrapy/Django compatibiltiy. I would love to spend more time on it, but just don't have the time atm.

I also admit that I am a bit disappointed how the existing pull requests went out, mostly good ideas but when I asked e.g. for additional testing and/or documentation, nothing came really back (not targeted at you, just a general observation).

I will add some branch structure to the repository though, maybe this makes contributions easier.

Cheers
Holger

**Comment by rakanalh** [comment]
Given that i use this package quite heavily in my projects, i can help you maintain this package.

**Comment by rakanalh** [comment]
I have a couple of ideas in mind for the development of this package:

1. This library lacks "XML Namespaces" support where i can define namespaces if i am scraping XML Atom feeds or any custom XML files.
2. My PR on scraping multiple values is still pending but i would love to see it integrated into the library... the idea is not to use TakeFirst as a default.
3. According to (2), scraping multiple images pops up on top of the list for what this library can do with multiple values of a single field. So DDS doesn't handle ManyToMany relations in it's core. I think we need to look at this one.

**Comment by bashu** [comment]
@holgerd77 , I can help you with =)

**Comment by holgerd77** [comment]
Hi @bashu, you are very welcome to help, but please provide a bit more description on what you are doing. If you are start working on feature enhancements or new features please go into discussion before on how things are implemented if side effects/backwards compatibility issues are to be expected.
