### ISSUE TITLE
Allow the user to customize the scraper

### ISSUE THREAD

**Issue by rylanchiu** [holgerd77/django-dynamic-scraper#53]
I am a newbie to web crawler. Now I am gong to build a django web app, in a part of which users fill up a form(keywords and time,etc.) and submit it. Then the scraper will begin to work and craw the data according to the user's requirement at a specific website(set by me). After that the data will pass to another model to do some clustering work. How can I do that?

**Comment by uditagarwal** [comment]
After I made the scraper as shown in the tutorial, I put the model work I had to do within the pipelines.py file since by then all the data is available.

**Comment by rylanchiu** [comment]
So It is not available at this moment?
By the way, when I did as you say in the DDS tutorial of creating model classes. I ran  python manage.py makemigrations craw(DDS belongs to this app). But there were errors:
SystemCheckError: System check identified some issues:

ERRORS:
craw.Article.checker_runtime: (fields.E300) Field defines a relation with model 'SchedulerRuntime', which is either not installed, or is abstract.
craw.NewsWebsite.scraper: (fields.E300) Field defines a relation with model 'Scraper', which is either not installed, or is abstract.
craw.NewsWebsite.scraper_runtime: (fields.E300) Field defines a relation with model 'SchedulerRuntime', which is either not installed, or is abstract.

**Comment by rylanchiu** [comment]
In addition, I got an error when I ran 
scrapy crawl article_spider -a id=1 -a do_action=yes

ImportError: No module named settings.

**Comment by holgerd77** [comment]
Hi @rylanchiu, if you have such specific requirements, I'm not sure, if ``django-dynamic-scraper`` is the right library for you, maybe you should deal with ``Scrapy`` directly?

Your last problem with the ``ImportError`` sound like a path problem, if he's not finding the ``settings.py`` file.

**Comment by rylanchiu** [comment]
I need to scrap js content. But scrapy seems to just enable me to get static content

**Comment by rylanchiu** [comment]
My path is as below, @holgerd77 :
-news
   |___scrapy.cfg
   |___cluster
   |___craw
              |___migrations
              ..........
              |___scraper
                         |____pipelines.py
                         |____settings.py
                         |____spiders.py
                         |____spiders.pyc
   |___news

**Comment by holgerd77** [comment]
Hmm, looks good, are you running the ``scrapy`` command from within the ``news`` directory?

If you want to scrape JS content, you can also use ``Scrapy`` with the ``Scrapy-Splash/JS`` library which is also used for scraping JS content in ``DDS``.

**Comment by cmwaura** [comment]
@rylanchiu , hey i dont know if this problem was resolved but i had the same issue with settings.py not  found. Incidentally i fixed this by adding an __init__.py file in the same directory are the settings.py file. I also changed the directory itself from scraper to another name then altered the scrapy.cfg file to the new name. 
@holgerd77  i really like this project and i see myself using it alot. If you dont mind me asking is there a way to follow links like the CrawlSpider?

**Comment by giangnm58** [comment]
my path as below:
├── scrapy.cfg
└── stack
    ├── __init__.py
    ├── items.py
    ├── pipelines.py
    ├── settings.py
    └── spiders
        └── __init__.py

i have same error with @rylanchiu
i try remove __init__.py but nothing happen.
@cmwaura can y tell about how to fix this error
thanks

**Comment by cmwaura** [comment]
@giangnm58 i would suggest checking the scrapy engine(scrapy.cfg) and try and figure out if its pointing directly to to settings.py   in the folder containing the spiders. if that is fine try and play around with the folder names you may have used the same folder name twice and thats why the engine is getting confused. If thats fine, check the SPIDER_MODULES in the settings.py and make sure that is configured properly like the this [example](https://github.com/holgerd77/django-dynamic-scraper/blob/master/example_project/open_news/scraper/settings.py). If all that is fine, hit me up and send me the source code i will look at it.

**Comment by cmwaura** [comment]
@holgerd77 so i have been religiously going through the documentation and it seems that you actually included the properties of crawl spider with the detail page on the django interface. Cheers

**Comment by holgerd77** [comment]
@cmwaura Hi Crispus, sorry for being so super-late with my answer.

1. Yes, an ``__init__.py`` file has generally to be in every folder with Python files to be interpreted as Python modules, that's a general Python thing, see:
http://stackoverflow.com/questions/448271/what-is-init-py-for

2. There is an open issue to integrate the flexibility of Scrapy ``CrawlSpider`` into ``DDS``, see https://github.com/holgerd77/django-dynamic-scraper/issues/11, no estimated time though when this will be implemented
