### ISSUE TITLE
Duplicates items

### ISSUE THREAD

**Issue by yunmanger1** [holgerd77/django-dynamic-scraper#56]
I am scraping news, and News model has a `link` field that is ID_FIELD, but it's not unique in database.

For some reason scraper stores duplicates. In general two duplicate items have time difference in 2-5 minutes. So I don't believe it's a race condition. I even tried to handle this situation in DjangoItem, but I still get duplicates. What might be the reason?

```
class NewsItem(DjangoItem):
    django_model = News

    def save(self, *a, **kw):
        link = self.instance.link
        existing = News.objects.filter(link=link).only('id').order_by('-ts').first()
        if existing:
            self.instance.pk = self.instance.id = existing.id
        instance = super(NewsItem, self).save(*a, **kw)
        return instance
```

**Comment by holgerd77** [comment]
Hi,
can you give an example of two datasets which are stored as duplicates in the database?

Disclaimer: Normally such questions are better discussed in the Google Group (https://groups.google.com/forum/#!forum/django-dynamic-scraper), issues are for development on the library itself
