### ISSUE TITLE
RuntimeWarning: DateTimeField Scraper.last_checker_delete received a naive datetime

### ISSUE THREAD

**Issue by bashu** [holgerd77/django-dynamic-scraper#65]
```python
/home/vagrant/.virtualenv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Scraper.last_checker_delete received a naive datetime (2016-05-25 11:30:25.292116) while time zone support is active.
  RuntimeWarning)
```

**Comment by holgerd77** [comment]
There is various use of ``datetime`` in the library ignoring Django timezone capabilities and I don't want to mix this up now being anxious to introduce side effects in library usage (time is a very sensitive thing in DDS). I would delay stuff like this for a later more comprehensive and tested update.
