### ISSUE TITLE
scrapyd return ERROR

### ISSUE THREAD

**Issue by XenoAura** [holgerd77/django-dynamic-scraper#68]
I try run scrapyd, but  received only
{"status": "error", "message": "spider 'article_checker' not found"}

```
conn.request("POST", "/schedule.json", params, headers)
conn.getresponse().read()
```

There is support scrapyd?

**Comment by holgerd77** [comment]
Please post such questions on the mailing list:
https://groups.google.com/forum/#!forum/django-dynamic-scraper
