### ISSUE TITLE
Problem with DDS+Postgresql

### ISSUE THREAD

**Issue by bezkos** [holgerd77/django-dynamic-scraper#84]
I found a problem that after each commit of DDS to its tables, there is below error in postgresql log file.

**LOG:  could not receive data from client: Connection reset by peer**

To fix it, i needed to close connection after commit like this:
In django_base_spider.py
```
from django.db import connection
def spider_closed(self):
     .....
     self.scheduler_runtime.save()
     connection.close()
    ......
```

**Comment by holgerd77** [comment]
Added this for ``v.0.12.2``.
