### ISSUE TITLE
multiple jsonpath

### ISSUE THREAD

**Issue by klkim** [holgerd77/django-dynamic-scraper#86]
Using jsonpath, is it possible to get multiple values in json-formatted return?
In common jsonpath notation, there is a [,] syntax to get multiple values from json, but DDS seems not to use that syntax. Any other method to get multiple values in one jsonpath-query in DDS?

Thank you.

**Comment by holgerd77** [comment]
In DDS ``v.0.12.2`` (couple of days) there will be a new ``use_default_procs`` attribute - set to ``True`` by default, which can be used to deactivate the default processors (``TakeFirst``, ``string_strip``). This was implemented for generally having more flexibility and not this special use case. Maybe this brings you closer to what you want to achieve anyhow and you might want to experiment with the new setting.

Cheers
Holger
