### ISSUE TITLE
DDS unusable with django >= 1.10

### ISSUE THREAD

**Issue by tigrus** [holgerd77/django-dynamic-scraper#87]
Django 1.11.1 : We unable to add request page type
![2017-05-14 16 34 55](https://cloud.githubusercontent.com/assets/804424/26034324/85dd8032-38c3-11e7-95d2-9a53bb597509.png)

Django 1.9.7 : We have ability to add request page type
![2017-05-14 16 36 26](https://cloud.githubusercontent.com/assets/804424/26034326/8bfbf9e4-38c3-11e7-9791-a4f1bdf4c910.png)

Looks like problem with registration of inline form for request page type

DDS version in both cases - 0.12

**Comment by holgerd77** [comment]
I think I once had a similar problem, probably you just have to hard-reload
the page and make sure, no cached content from the old Django version is
loaded.

Am 14.05.2017 15:38 schrieb "Nikolay Fominykh" <notifications@github.com>:

**Comment by tigrus** [comment]
@holgerd77 of course I did it, before submitting issue. And rechecked by your request - no, hard reset not helping.

**Comment by holgerd77** [comment]
Still think it's a caching issue. If I remember correct, I think what helped for me was directly open the admin-related JS files and reload them, could see the underlying source code change. Maybe try that.
