### ISSUE TITLE
Zero actions counter and Standard Update

### ISSUE THREAD

**Issue by bezkos** [holgerd77/django-dynamic-scraper#88]
When u set a field as Standard Update and there are new updates on that specific field then zero actions counter keep increasing +1 instead of staying in previous value. 
With current state, dynamic scheduling will go to max_time even if there are regular updates on Standard Update field.

**Comment by holgerd77** [comment]
Seems to be a good point, will see if I can bring this into the next minor
upgrade.

Thanks for reporting!

Holger

2017-05-31 2:34 GMT+02:00 bezkos <notifications@github.com>:

**Comment by holgerd77** [comment]
Hi, I've added this for the upcoming ``v.0.12.2`` release (couple of days). A field update is now also treated as a successful action causing the zero actions counter to reset, so working with scheduling when using ``STANDARD (UPDATE)`` fields should now work more like one would expect.
