### ISSUE TITLE
Scraping in time

### ISSUE THREAD

**Issue by moreplavec** [holgerd77/django-dynamic-scraper#98]
Is it possible to run scraper, but not to rewrite scraped data, but keep them in time? For example, i want to scrape prices for hundreds of products on more websites and keep data in time. Is it possible make URL and date as unique param?

**Comment by holgerd77** [comment]
You don't have to use the ``url`` as an id field in your scraped object class (Django admin). Choose something else as id field (also several together possible) which stays unique.
