### ISSUE TITLE
How to scrape a JSON object instead of a JSON object inside a list?

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [holgerd77/django-dynamic-scraper#99]
I noticed that in your news json data source.. You guys are scraping the data inside a list like `[{"attachments":[],"body":"Dear Friends and Colleagues}, {}, {}]`. I was wondering how to scrape if the data being scraped is an actual object like inside my json is exactly {"first_name": "Dean", "second_name": "Christian", "middle_name": "Guinto", "last_name": "Armada"}. Is there something in the docs to save/scrape this type of json file?

PS.
I already tried scraping a json data inside the list like `{"data": [{"name":"data1"}, {"name": "data2"}]}` and it perfectly works

**Comment by holgerd77** [comment]
Please don't use GitHub issues for support questions, post on the mailing list instead:
https://groups.google.com/forum/#!forum/django-dynamic-scraper

Not sure if I understand your question correctly, JSON object attributes can be scraped with dotted notation, ``objectName.last_name`` e.g..
